### ISSUE TITLE
Lost all my scripts

### ISSUE THREAD

**Issue by iamfnd** [rsms/scripter#10]
![Screenshot 2020-09-29 at 11 50 11 AM](https://user-images.githubusercontent.com/2055952/94513877-06cf0c80-024a-11eb-8524-142128781e0d.png)

Not sure what happened, but I loaded Scripter today and all my customs scripts are no longer available. How can I retrieve them? 😢

**Comment by rsms** [comment]
First off, I'm sorry this happened!

Scripter stores its scripts in the browser's (or Figma desktop app's) local storage, specifically IndexedDB. So if you are using a different browser you may want to open the one you used before and download your scripts to transfer them. Another possibility is that you manually deleted your browser's local storage, for example by using Chrome's "Clear Browsing Data" function.

If you are using the Figma desktop app and you didn't do any of the above, it may be a bug in Figma. If so, please reach out to Figma customer support using the "(?)" icon in the bottom right of the screen inside Figma (or email `support@figma.com`)

To download a zip archive of all your scripts, scroll to the bottom of the sidebar menu and select "Export all scripts".

---

Unfortunately Figma does not provide any form of user identifier that could be used for building a central server-based storage. One day I might implement all that myself (user accounts, auth, etc.) but it's a lot of work and requires running a custom server which cost a lot of time and money. My hope is that Figma adds an anonymized user ID to their API.

**Comment by iamfnd** [comment]
Thanks for replying, for context--I primarily use the Desktop app, I have also gotten in touch with support and apparently it is a known issue where a password reset requests logs you out of the app and then clears all local plug-in data. Sadly, this wasn't made known to me and therefore no opportunity to backup.

**Comment by rsms** [comment]
I'm sorry! I hope Figma can fix their bug in the desktop app (I used to work at Figma and with the desktop app; I know the cause of the bug and it's totally fixable)
