### ISSUE TITLE
Cloudflare seems to be blocking .ts files

### ISSUE THREAD

**Issue by rzuppur** [rsms/scripter#20]
Scripter is broken for me, loading spinner never stops and UI is frozen. Console has this and more similar errors for different .ts files

`scripter.rsms.me/:1 Access to fetch at 'https://www.cloudflare-terms-of-service-abuse.com/stream.mp4' (redirected from 'https://scripter.rsms.me/lib.dom.d.ts?v=+EviNZmp2POY3vxI1MwvwLsktEk') from origin 'https://scripter.rsms.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I'm guessing since `ts` is also a video transport stream file extension, some dumb filter at Cloudflare thinks you are serving video and blocks the request?

**Comment by 6220119** [comment]
The issue with CloudFlare seems to be resolved already. But a new one shows up: Invalid Certificate, so the plugin cannot be started.
At the moment, I have to work around it by disabling security check.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/1059583/229712908-cf00654b-2d8a-42bb-a88c-12c7d8564187.png">

**Comment by rsms** [comment]
I disabled Cloudflare caching. They had severe performance issues. The SSL issue was a bug on GitHub’s end and should be fixed now.

**Comment by rsms** [comment]
Weeeellll I had to re-enable CF since GH has some bug re SSL & DNS. See #21

**Comment by rsms** [comment]
I'm imagining a fix being to rename all .ts files that are loaded at runtime to .ts.txt and making sure they are properly recognized as TypeScript by Monaco in Scripter.

**Comment by rsms** [comment]
I was able to fix the GitHub SSL issues and now the .ts files seem to be loading again. Please confirm that/if this solved your issues!

<img width="742" alt="Screen Shot 2023-04-05 at 16 32 37" src="https://user-images.githubusercontent.com/47046/230235717-fc1b930a-db61-4ebc-9594-2f6884f86d75.png">

**Comment by rzuppur** [comment]
Seems to be working, thanks! Good to know that this plugin is still being maintained

**Comment by rsms** [comment]
:•)
