### ISSUE TITLE
Certificate issue on scripter.rsms.me

### ISSUE THREAD

**Issue by yoonbuck** [rsms/scripter#21]
Hi, you mentioned yesterday that the SSL issue was a bug on GitHub's end and should be fixed. Unfortunately, I am still getting errors loading `scripter.rsms.me` as the certificate is for `*.github.io`. Because of this, the plugin can't be opened in the desktop app. (The network tab shows the request fails with net:ERR_CERT_COMMON_NAME_INVALID)

<img width="650" alt="image" src="https://user-images.githubusercontent.com/46464916/230226926-21fd0fbc-80a1-4716-9001-11f4301016b9.png">

(I'm opening a new issue since this is different from the Cloudflare problem that seems to be resolved, I hope that's okay.)

**Comment by rsms** [comment]
Looking into it...

**Comment by rsms** [comment]
It's served by GitHub pages and I see this confusing error in settings:

<img width="852" alt="Screen Shot 2023-04-05 at 16 05 53" src="https://user-images.githubusercontent.com/47046/230231053-8118aa88-c1a2-4f81-a1fe-f0fc5c0ed10d.png">

Can't find information about that "error" message in GitHubs documentation so I have no idea what to do (until a few days ago Scripter was hosted by Cloudflare but that had some serious issues and I had to disable it. I'm going to look into enabling that again.)

**Comment by rsms** [comment]
Okay, should be back up now, served by CF instead of GH

<img width="818" alt="Screen Shot 2023-04-05 at 16 12 51" src="https://user-images.githubusercontent.com/47046/230231853-0fc353b0-9303-4f9c-a339-4b147de4ecfa.png">

**Comment by rsms** [comment]
Found this helpful. Have made the change to DNS and now waiting for GH to update. https://github.com/orgs/community/discussions/23049

**Comment by rsms** [comment]
Well, that doesn't work either. I guess SSL on subdomains is just broken with GitHub pages.

<img width="895" alt="Screen Shot 2023-04-05 at 16 21 27" src="https://user-images.githubusercontent.com/47046/230233008-8dc441a3-8608-417e-96c3-de44cc84daf8.png">

**Comment by rsms** [comment]
Removed everything from DNS records to GitHub setting and started over, doing exactly what I've done before. And... it worked? Lol. Okay, let me know if you experience any more issues!

<img width="615" alt="Screen Shot 2023-04-05 at 16 29 42" src="https://user-images.githubusercontent.com/47046/230234927-71f6605b-571d-4c77-9399-d9a8594307ef.png">

**Comment by yoonbuck** [comment]
Sweet, Scripter is back! Thanks so much for getting this sorted out.
