### ISSUE TITLE
"Save to Figma file" button doesn't work at Figma Mac App

### ISSUE THREAD

**Issue by dinozavrix** [rsms/scripter#7]
After pushing "Save to Figma file" at Figma Mac App nothing happens
Same button at Chrome browser works fine
Figma Desktop App release 86, Build 4
macOS Mojave 10.14.16

P.S. Thank you for amazing plugin

**Comment by rsms** [comment]
Could you please provide a detailed list of steps you take, from opening Figma until the save button not working. Thank you.

**Comment by rsms** [comment]
Closing this as stale. Happy to reopen if more detailed reproduction details can be provided.

**Comment by dinozavrix** [comment]
The problem was in the fonts, if not the latest version of Inter is installed, then the scripter freezes while trying to create an element for the script
