### ISSUE TITLE
How to expand function's signature tooltip?

### ISSUE THREAD

**Issue by fredthedead** [rsms/scripter#8]
When getting the tooltip for a function's signature, what's the best way to expand it to see the full list of parameters
![image](https://user-images.githubusercontent.com/19219041/87244462-ebd9d100-c480-11ea-9f71-316cfd8a782b.png)
(the "...71 more..." )

**Comment by rsms** [comment]
I don't think it's possible. Scripter uses the VS Code editor which is called "Monaco" when used free-standing. You could try asking here: https://github.com/Microsoft/monaco-editor

**Comment by fredthedead** [comment]
thank you
